// Command genkeys regenerates the known Quadlet key set from the installed
// podman-systemd.unit(5) manual page.
//
// Per ADR-0002, QD042 reports only keys that exist in no released Quadlet, and
// the table backing it is generated rather than hand-maintained. A stale
// hand-written table produces confident, wrong findings, which for a linter is
// worse than producing none.
//
// Run it with:
//
//	go run ./internal/rules/genkeys -out internal/rules/keys_generated.go
//
// on a machine with podman-docs installed, and commit the result.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
)

var (
	sectionPattern = regexp.MustCompile(`(?m)^(\w[\w ]*units \[(\w+)\])`)
	keyPattern     = regexp.MustCompile(`(?m)^   ([A-Z][A-Za-z0-9]*)=`)
)

func main() {
	out := flag.String("out", "", "file to write (default stdout)")
	flag.Parse()

	page, err := manPage()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genkeys: %v\n", err)
		os.Exit(1)
	}

	sections := parse(page)
	if len(sections) == 0 {
		fmt.Fprintln(os.Stderr, "genkeys: no unit sections found; is podman-docs installed?")
		os.Exit(1)
	}

	source := render(sections, podmanVersion())
	if *out == "" {
		fmt.Print(source)
		return
	}
	if err := os.WriteFile(*out, []byte(source), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genkeys: writing %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s from podman-systemd.unit(5)\n", *out)
}

func manPage() (string, error) {
	cmd := exec.Command("man", "podman-systemd.unit")
	cmd.Env = append(os.Environ(), "MANWIDTH=80")

	data, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("reading podman-systemd.unit(5): %w", err)
	}
	return string(data), nil
}

func podmanVersion() string {
	data, err := exec.Command("podman", "--version").Output()
	if err != nil {
		return "unknown"
	}
	fields := strings.Fields(string(data))
	if len(fields) < 3 {
		return "unknown"
	}
	return fields[2]
}

type section struct {
	Name string
	Keys []string
}

// parse extracts each unit type's keys from the manual page. Keys are indented
// by three spaces at the start of their definition, which is how the page
// distinguishes a key from prose that happens to mention one.
func parse(page string) []section {
	matches := sectionPattern.FindAllStringSubmatchIndex(page, -1)

	var out []section
	for i, m := range matches {
		end := len(page)
		if i+1 < len(matches) {
			end = matches[i+1][0]
		}

		name := page[m[4]:m[5]]
		seen := map[string]bool{}
		var keys []string
		for _, k := range keyPattern.FindAllStringSubmatch(page[m[0]:end], -1) {
			if !seen[k[1]] {
				seen[k[1]] = true
				keys = append(keys, k[1])
			}
		}
		sort.Strings(keys)

		out = append(out, section{Name: name, Keys: keys})
	}
	return out
}

func render(sections []section, version string) string {
	var b strings.Builder

	b.WriteString("// Code generated by internal/rules/genkeys. DO NOT EDIT.\n//\n")
	fmt.Fprintf(&b, "// Extracted from podman-systemd.unit(5) as shipped with Podman %s.\n", version)
	b.WriteString("// Regenerate with:\n//\n")
	b.WriteString("//\tgo run ./internal/rules/genkeys -out internal/rules/keys_generated.go\n\n")
	b.WriteString("package rules\n\n")

	fmt.Fprintf(&b, "// generatedFromPodman records which Podman release the key set came from,\n")
	fmt.Fprintf(&b, "// so a finding can say what it was checked against.\n")
	fmt.Fprintf(&b, "const generatedFromPodman = %q\n\n", version)

	b.WriteString("// knownKeys maps each Quadlet unit section to the keys it accepts.\n")
	b.WriteString("var knownKeys = map[string]map[string]bool{\n")
	for _, s := range sections {
		fmt.Fprintf(&b, "\t%q: {\n", s.Name)
		for _, k := range s.Keys {
			fmt.Fprintf(&b, "\t\t%q: true,\n", k)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	return b.String()
}
