// Package generate turns a compose project into Quadlet units.
//
// Two commitments shape the output. First, every non-obvious translation
// decision is annotated in the unit itself, because the person reading the unit
// in six months is the one who needs to know why it says what it says. Second,
// nothing is dropped silently: a compose feature that cannot be translated
// becomes a finding, never an omission.
//
// The default shape is one .container per service plus a shared .network, per
// ADR-0001. That is not a stylistic choice: Podman's default network has DNS
// disabled, so without a user-defined network, sibling service names do not
// resolve and the compose semantics are lost.
package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/MatrixMagician/quaddoc/internal/parse/compose"
)

// Options control conversion.
type Options struct {
	// Pod emits a single .pod unit that every container joins, instead of a
	// shared .network. Containers in a pod share a network namespace and
	// reach each other on localhost.
	Pod bool
	// Annotate writes explanatory comments into the generated units.
	// On by default; tests that compare exact bytes may turn it off.
	Annotate bool
}

// Unit is a generated unit file.
type Unit struct {
	// Name is the file name, e.g. `web.container`.
	Name string
	// Content is the file's text.
	Content string
}

// Result is everything a conversion produced.
type Result struct {
	Units []Unit
	// Notes are translation decisions worth reporting to the user, beyond
	// what is annotated in the files.
	Notes []Note
}

// Note is a translation decision or an untranslatable feature.
type Note struct {
	// Unit is the generated unit it concerns, empty for project-wide notes.
	Unit string
	// Message states what happened.
	Message string
	// Severity is `error`, `warning`, or `note`.
	Severity string
}

// builder accumulates a unit file's text.
type builder struct {
	annotate bool
	b        strings.Builder
	section  string
}

func (u *builder) comment(format string, args ...any) {
	if !u.annotate {
		return
	}
	for _, line := range wrap(fmt.Sprintf(format, args...), 74) {
		if line == "" {
			// A bare "#" rather than "# ", so the file carries no trailing
			// whitespace.
			u.b.WriteString("#\n")
			continue
		}
		fmt.Fprintf(&u.b, "# %s\n", line)
	}
}

func (u *builder) sectionHeader(name string) {
	if u.b.Len() > 0 {
		u.b.WriteByte('\n')
	}
	fmt.Fprintf(&u.b, "[%s]\n", name)
	u.section = name
}

func (u *builder) key(key, value string) {
	if value == "" {
		return
	}
	fmt.Fprintf(&u.b, "%s=%s\n", key, value)
}

func (u *builder) keys(key string, values []string) {
	for _, v := range values {
		u.key(key, v)
	}
}

func (u *builder) String() string { return u.b.String() }

// wrap breaks a comment into lines of at most width characters, so annotations
// stay readable in a terminal.
func wrap(s string, width int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return []string{""}
	}

	var lines []string
	current := words[0]
	for _, w := range words[1:] {
		if len(current)+1+len(w) > width {
			lines = append(lines, current)
			current = w
			continue
		}
		current += " " + w
	}
	return append(lines, current)
}

// Convert turns a compose project into Quadlet units.
func Convert(p *compose.Project, opts Options) *Result {
	result := &Result{}

	// Untranslatable compose features are reported before anything else, so
	// the user sees them even if generation then fails.
	for _, un := range p.Unsupported {
		unit := ""
		if un.Service != "" {
			unit = un.Service + ".container"
		}
		result.Notes = append(result.Notes, Note{
			Unit:     unit,
			Severity: "warning",
			Message:  fmt.Sprintf("compose key %q is not translated: %s", un.Key, un.Reason),
		})
	}

	networkUnit := p.Name + "-net"

	if opts.Pod {
		result.Units = append(result.Units, generatePod(p, opts))
	} else {
		result.Units = append(result.Units, generateNetwork(p, networkUnit, opts))
	}

	for _, v := range p.Volumes {
		if v.External {
			result.Notes = append(result.Notes, Note{
				Severity: "note",
				Message: fmt.Sprintf("volume %q is external, so no .volume unit was generated; "+
					"create it yourself with `podman volume create %s`", v.Name, v.Name),
			})
			continue
		}
		result.Units = append(result.Units, generateVolume(v, opts))
	}

	for _, s := range p.Services {
		unit, notes := generateContainer(p, s, networkUnit, opts)
		result.Units = append(result.Units, unit)
		result.Notes = append(result.Notes, notes...)
	}

	sort.Slice(result.Units, func(i, j int) bool { return result.Units[i].Name < result.Units[j].Name })
	return result
}

func generateNetwork(p *compose.Project, name string, opts Options) Unit {
	var u builder
	u.annotate = opts.Annotate

	u.comment("Generated by quaddoc from a compose project.")
	u.comment("")
	u.comment("Compose gives every service a DNS name that its siblings can resolve. " +
		"Podman's default network has DNS disabled, so a shared user-defined " +
		"network like this one is required to preserve that behaviour, not merely " +
		"a tidier way to arrange things.")
	u.comment("")
	u.comment("Podman names the network created by this unit `systemd-%s`.", name)

	u.sectionHeader("Network")
	u.key("NetworkName", p.Name)

	// Carry across the driver and addressing of a compose network when one
	// was configured explicitly.
	for _, n := range p.Networks {
		if n.External {
			continue
		}
		if n.Driver != "" && n.Driver != "bridge" {
			u.key("Driver", n.Driver)
		}
		if n.Internal {
			u.key("Internal", "true")
		}
		for _, subnet := range n.Subnets {
			u.key("Subnet", subnet)
		}
		u.key("Gateway", n.Gateway)
		break
	}

	u.sectionHeader("Install")
	u.key("WantedBy", "default.target")

	return Unit{Name: name + ".network", Content: u.String()}
}

func generatePod(p *compose.Project, opts Options) Unit {
	var u builder
	u.annotate = opts.Annotate

	u.comment("Generated by quaddoc from a compose project.")
	u.comment("")
	u.comment("Containers in a pod share a network namespace, so they reach each " +
		"other on localhost rather than by service name. Where the compose file " +
		"relied on service-name DNS, those references need changing to localhost.")

	u.sectionHeader("Pod")
	u.key("PodName", p.Name)

	for _, s := range p.Services {
		for _, port := range s.Ports {
			// In a pod, ports are published by the pod, not by its members.
			u.key("PublishPort", port.PublishedPort())
		}
	}

	u.sectionHeader("Install")
	u.key("WantedBy", "default.target")

	return Unit{Name: p.Name + ".pod", Content: u.String()}
}

func generateVolume(v compose.Volume, opts Options) Unit {
	var u builder
	u.annotate = opts.Annotate

	u.comment("Generated by quaddoc from a compose project.")
	u.comment("")
	u.comment("Podman names the volume created by this unit `systemd-%s`. Reference "+
		"it from a container as `%s.volume`, not by the bare name.", v.Name, v.Name)

	u.sectionHeader("Volume")
	u.key("VolumeName", v.Name)
	u.key("Driver", v.Driver)

	for _, k := range sortedKeys(v.Options) {
		// Quadlet expresses local-driver bind options as its own keys rather
		// than passing them through verbatim.
		switch k {
		case "type":
			u.key("Type", v.Options[k])
		case "device":
			u.key("Device", v.Options[k])
		case "o":
			u.key("Options", v.Options[k])
		default:
			u.key("PodmanArgs", fmt.Sprintf("--opt %s=%s", k, v.Options[k]))
		}
	}
	for _, k := range sortedKeys(v.Labels) {
		u.key("Label", fmt.Sprintf("%s=%s", k, v.Labels[k]))
	}

	return Unit{Name: v.Name + ".volume", Content: u.String()}
}

func generateContainer(p *compose.Project, s compose.Service, networkUnit string, opts Options) (Unit, []Note) {
	var u builder
	var notes []Note
	u.annotate = opts.Annotate

	u.comment("Generated by quaddoc from compose service %q.", s.Name)

	u.sectionHeader("Unit")
	u.key("Description", fmt.Sprintf("%s (from compose service %s)", s.Name, s.Name))

	// depends_on becomes systemd ordering, which is weaker than what compose
	// promises. Say so rather than let the difference be discovered in
	// production.
	for _, dep := range s.DependsOn {
		target := dep.Service + ".service"
		switch dep.Condition {
		case "service_healthy":
			u.comment("")
			u.comment("compose had `depends_on: %s: condition: service_healthy`. systemd "+
				"orders units but does not gate on health, so After= alone starts this "+
				"container as soon as %s has *started*, not once it is healthy. To close "+
				"the gap, set Notify=healthy on %s.container together with a healthcheck: "+
				"its service then reports started only once Podman marks it healthy.",
				dep.Service, dep.Service, dep.Service)
			notes = append(notes, Note{
				Unit:     s.Name + ".container",
				Severity: "warning",
				Message: fmt.Sprintf("depends_on %s used condition: service_healthy, which systemd "+
					"ordering cannot express; see the comment in the generated unit", dep.Service),
			})
		case "service_completed_successfully":
			u.comment("")
			u.comment("compose had `depends_on: %s: condition: "+
				"service_completed_successfully`. That maps to After= plus a Requires= on "+
				"a unit that runs to completion; check that %s.container is a one-shot.",
				dep.Service, dep.Service)
		}
		u.key("After", target)
		u.key("Requires", target)
	}

	u.sectionHeader("Container")
	u.key("ContainerName", s.Name)
	u.key("Image", s.Image)

	if len(s.Entrypoint) > 0 {
		u.key("Entrypoint", strings.Join(s.Entrypoint, " "))
	}
	if len(s.Command) > 0 {
		// Quadlet's Exec= is the command, matching compose's `command:`.
		u.key("Exec", strings.Join(s.Command, " "))
	}

	if s.User != "" {
		user, group, hasGroup := strings.Cut(s.User, ":")
		u.key("User", user)
		if hasGroup {
			u.key("Group", group)
		}
	}

	u.key("WorkingDir", s.WorkingDir)
	u.key("HostName", s.Hostname)

	for _, env := range s.Environment {
		u.key("Environment", fmt.Sprintf("%s=%s", env.Name, env.Value))
	}

	for _, m := range s.Volumes {
		value, note := renderMount(p, s, m)
		if note != "" {
			u.comment("")
			u.comment("%s", note)
		}
		u.key("Volume", value)
	}

	if !opts.Pod {
		for _, port := range s.Ports {
			u.key("PublishPort", port.PublishedPort())
		}
		u.key("Network", networkUnit+".network")
	} else {
		u.comment("")
		u.comment("Ports are published by the pod, not by its members.")
		u.key("Pod", p.Name+".pod")
	}

	u.keys("AddCapability", s.CapAdd)
	u.keys("DropCapability", s.CapDrop)
	u.keys("AddDevice", s.Devices)
	u.keys("DNS", s.DNS)
	u.keys("GroupAdd", s.GroupAdd)
	u.keys("Tmpfs", s.Tmpfs)

	if s.ReadOnly {
		u.key("ReadOnly", "true")
	}
	if s.Privileged {
		u.comment("")
		u.comment("compose set `privileged: true`. This disables most container isolation; " +
			"consider whether specific AddCapability= or AddDevice= entries would do.")
		u.key("PodmanArgs", "--privileged")
		notes = append(notes, Note{
			Unit:     s.Name + ".container",
			Severity: "warning",
			Message:  "service runs privileged, which disables most container isolation",
		})
	}
	u.key("StopSignal", s.StopSignal)
	if s.ShmSize != "" {
		u.key("ShmSize", s.ShmSize)
	}
	for _, k := range sortedKeys(s.Sysctls) {
		u.key("Sysctl", fmt.Sprintf("%s=%s", k, s.Sysctls[k]))
	}
	for _, k := range sortedKeys(s.Labels) {
		u.key("Label", fmt.Sprintf("%s=%s", k, s.Labels[k]))
	}

	if hc := s.HealthCheck; hc != nil && !hc.Disabled {
		cmd := healthCommand(hc.Test)
		if cmd != "" {
			u.key("HealthCmd", cmd)
			u.key("HealthInterval", hc.Interval)
			u.key("HealthTimeout", hc.Timeout)
			u.key("HealthStartPeriod", hc.StartPeriod)
			if hc.Retries > 0 {
				u.key("HealthRetries", fmt.Sprintf("%d", hc.Retries))
			}
		}
	} else if hc != nil && hc.Disabled {
		u.comment("")
		u.comment("compose disabled the healthcheck with `healthcheck: disable: true`.")
		u.key("HealthCmd", "none")
	}

	u.sectionHeader("Service")
	restart, note := renderRestart(s.Restart)
	if note != "" {
		// The comment belongs above the key, so rebuild the section.
		u.comment("")
		u.comment("%s", note)
		notes = append(notes, Note{
			Unit:     s.Name + ".container",
			Severity: "note",
			Message:  note,
		})
	}
	u.key("Restart", restart)

	u.sectionHeader("Install")
	u.key("WantedBy", "default.target")

	return Unit{Name: s.Name + ".container", Content: u.String()}, notes
}

// renderMount turns a compose mount into a `Volume=` value, and returns an
// annotation when the translation was not obvious.
func renderMount(p *compose.Project, s compose.Service, m compose.Mount) (string, string) {
	var options []string
	if m.ReadOnly {
		options = append(options, "ro")
	}

	switch m.Type {
	case "volume":
		// A named volume declared in the compose file becomes a `.volume`
		// unit reference, so the generated units carry the dependency.
		source := m.Source
		note := ""
		if declared(p, m.Source) {
			source = m.Source + ".volume"
			note = fmt.Sprintf("Named volume %q refers to the %s.volume unit, which Podman "+
				"materialises as a volume called `systemd-%s`. The .volume suffix is what "+
				"creates the dependency between the two units.", m.Source, m.Source, m.Source)
		}
		if m.SELinux != "" {
			options = append(options, m.SELinux)
		}
		return join(source, m.Target, options), note

	case "tmpfs":
		return join("", m.Target, options), ""

	default: // bind
		if m.SELinux != "" {
			options = append(options, m.SELinux)
			return join(m.Source, m.Target, options), ""
		}
		// Deliberately not guessing at a label here: whether the mount wants
		// `:z` or `:Z` depends on whether other units share the source, which
		// is a project-wide question the rule engine answers. QD001 reports
		// it, and `quaddoc fix` applies it.
		return join(m.Source, m.Target, options),
			fmt.Sprintf("Bind mount of %s. On an SELinux system this needs a relabelling "+
				"option, `:Z` for a source used by this container alone or `:z` for one "+
				"shared with others. quaddoc does not guess: run `quaddoc lint` to see "+
				"which applies, and `quaddoc fix` to apply it.", m.Source)
	}
}

// declared reports whether a named volume was declared at the top level of the
// compose file, and so has a generated `.volume` unit.
func declared(p *compose.Project, name string) bool {
	for _, v := range p.Volumes {
		if v.Name == name && !v.External {
			return true
		}
	}
	return false
}

func join(source, target string, options []string) string {
	var parts []string
	if source != "" {
		parts = append(parts, source)
	}
	parts = append(parts, target)
	value := strings.Join(parts, ":")
	if len(options) > 0 {
		value += ":" + strings.Join(options, ",")
	}
	return value
}

// renderRestart maps a compose restart policy onto systemd's, and explains the
// one that has no exact equivalent.
func renderRestart(policy string) (string, string) {
	switch policy {
	case "", "no":
		return "no", ""
	case "always":
		return "always", ""
	case "on-failure":
		return "on-failure", ""
	case "unless-stopped":
		// systemd has no policy that means "restart unless a human stopped
		// it". Restart=always is the closest, and differs only in that a
		// manual `systemctl stop` is respected until the next boot, whereas
		// compose would leave the container stopped across a daemon restart.
		return "always", "compose used `restart: unless-stopped`, which systemd cannot " +
			"express exactly. Restart=always is the closest: systemd honours an explicit " +
			"`systemctl stop` for as long as the machine stays up, and starts the unit " +
			"again at boot because of the [Install] section."
	default:
		if strings.HasPrefix(policy, "on-failure") {
			return "on-failure", ""
		}
		return "always", fmt.Sprintf("compose restart policy %q was not recognised; "+
			"Restart=always was used.", policy)
	}
}

// healthCommand renders a compose healthcheck test as a shell command.
//
// compose's forms are `["CMD", "a", "b"]` for a direct exec, `["CMD-SHELL",
// "..."]` for a shell command, and `["NONE"]` to disable.
func healthCommand(test []string) string {
	if len(test) == 0 {
		return ""
	}
	switch test[0] {
	case "NONE":
		return ""
	case "CMD":
		return strings.Join(test[1:], " ")
	case "CMD-SHELL":
		return strings.Join(test[1:], " ")
	default:
		return strings.Join(test, " ")
	}
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
